namespace Synth
open Synth
open Variables

module Songs =

    let MoonSong () : float list =
        let mutable MoonTune = Wave.MakeNote (Wave.Sine) 0.5 Note.C 4
        MoonTune <- MoonTune @ Wave.MakeNote (Wave.Sine) 0.5 Note.C 4
        MoonTune <- MoonTune @ Wave.MakeNote (Wave.Sine) 0.5 Note.C 4
        MoonTune <- MoonTune @ Wave.MakeNote (Wave.Sine) 0.5 Note.D 4
        MoonTune <- MoonTune @ Wave.MakeNote (Wave.Sine) 1. Note.E 4
        MoonTune <- MoonTune @ Wave.MakeNote (Wave.Sine) 1. Note.D 4
        MoonTune <- MoonTune @ Wave.MakeNote (Wave.Sine) 0.5 Note.C 4
        MoonTune <- MoonTune @ Wave.MakeNote (Wave.Sine) 0.5 Note.E 4
        MoonTune <- MoonTune @ Wave.MakeNote (Wave.Sine) 0.5 Note.D 4
        MoonTune <- MoonTune @ Wave.MakeNote (Wave.Sine) 0.5 Note.D 4
        MoonTune <- MoonTune @ Wave.MakeNote (Wave.Sine) 1. Note.C 4
        MoonTune <- MoonTune @ Wave.MakeNote (Wave.Sine) 1. Note.DEBUG 4

        MoonTune


    let PirateOfCaraiban () : float list =
    
            let mutable HesAPirate = Wave.MakeNote (Wave.Sine) 0.5 Note.DEBUG 0
            
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.D 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.D 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.D 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.D 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.D 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.D 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.D 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.D 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.D 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.D 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.D 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.D 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.D 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.D 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.D 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.D 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.D 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.D 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.D 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.D 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.D 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.D 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.D 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.D 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.D 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.A 3
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.C 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.D 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.D 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.D 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.E 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.F 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.F 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.F 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.G 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.E 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.E 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.D 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.C 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.C 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.D 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.DEBUG 0
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.A 3
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.C 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.D 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.D 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.D 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.E 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.F 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.F 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.F 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.G 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.E 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.E 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.D 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.C 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.D 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.DEBUG 0
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.A 3
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.C 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.D 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.D 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.D 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.F 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.G 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.G 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.G 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.A 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.Ad 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.Ad 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.A 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.G 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.A 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.D 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.DEBUG 0
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.D 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.E 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.F 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.F 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.G 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.A 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.D 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.DEBUG 0
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.D 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.F 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.E 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.E 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.F 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.D 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.E 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.DEBUG 0
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.A 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.C 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.D 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.D 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.D 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.E 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.F 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.F 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.F 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.G 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.E 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.E 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.D 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.C 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.C 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.D 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.DEBUG 0
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.A 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.C 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.D 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.D 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.D 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.E 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.F 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.F 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.F 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.G 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.E 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.E 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.D 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.C 5 
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.D 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.DEBUG 0
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.A 4
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.C 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.D 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.D 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.D 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.F 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.G 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.G 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.G 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.A 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.Ad 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.Ad 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.A 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.G 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.A 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.D 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.DEBUG 0
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.D 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.E 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.F 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.F 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.G 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.A 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.D 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.DEBUG 0
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.D 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.F 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.E 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.E 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.D 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.C 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.D 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.D 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.E 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.F 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.F 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.F 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 1. Note.G 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 4. Note.A 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.F 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 0.5 Note.D 5
            HesAPirate <- HesAPirate @ Wave.MakeNote (Wave.Sine) 3. Note.A 4
    
            HesAPirate


    let Doom () : float list =
        let mutable AtHellGates = Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Cd 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.B 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.250 Note.A 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Ad 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.B 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Cd 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.B 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.25 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.5 Note.A 3
        
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Cd 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.B 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.250 Note.A 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Ad 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.B 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Cd 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.B 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.25 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.5 Note.A 3

        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Cd 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.B 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.250 Note.A 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Ad 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.B 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Cd 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.B 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.25 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.5 Note.A 3

        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Cd 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.B 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.250 Note.A 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Ad 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.B 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Cd 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3

        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.0625 Note.F 5
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.0625 Note.Dd 5
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.0625 Note.F 5
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.0625 Note.Fd 5
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.0625 Note.D 5
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.0625 Note.Fd 5
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.0625 Note.Ad 5
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.0625 Note.Fd 5
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.0625 Note.D 5

        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Cd 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.B 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.A 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.250 Note.D 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Ad 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.B 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Cd 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.B 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.5 Note.A 3

        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Cd 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.B 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.250 Note.A 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Ad 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.B 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Cd 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.B 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.25 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.5 Note.A 3

        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Cd 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.B 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.A 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.25 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Ad 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.B 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Cd 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3

        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Ad 5
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Fd 5
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Ad 5
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Fd 5
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 6
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Fd 5
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Ad 5
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 6

        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Gd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Gd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Gd 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Gd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Gd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Fd 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Gd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Gd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.E 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Gd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Gd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.D 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Gd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Gd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.E 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Gd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Gd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Gd 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Gd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Gd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Fd 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Gd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Gd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.E 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Gd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Gd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.5 Note.D 4

        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Gd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Gd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Gd 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Gd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Gd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Fd 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Gd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Gd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.E 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Gd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Gd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.D 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Gd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Gd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.E 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Gd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Gd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Gd 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Gd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Gd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Fd 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Fd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Fd 3

        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.0625 Note.Dd 5
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.0625 Note.Cd 5
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.0625 Note.Dd 5
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.0625 Note.B 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.0625 Note.Gd 5
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.0625 Note.Dd 5
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.0625 Note.Dd 5
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.0625 Note.Gd 4

        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Cd 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.B 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.250 Note.A 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Ad 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.B 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Cd 4
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.B 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.125 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.25 Note.Dd 3
        AtHellGates <- AtHellGates @ Wave.MakeNote (Wave.Sine) 0.5 Note.A 3

        AtHellGates


